apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cake-delight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: subbaiahkv/cakedelight-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"

            - name: MONGO_URI
              value: "mongodb://order-mongo:27017/order_db"

            - name: RABBITMQ_URL
              value: "amqp://cakeadmin:cakepass@rabbitmq:5672"

            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:4001"
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 4002
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"
          