apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "cakeadmin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "cakepass"