apiVersion: v1
kind: Secret
metadata:
  name: notification-email-secret
  namespace: cake-delight
type: Opaque
stringData:
  EMAIL_USER: "venkatasubbaiahkummari@gmail.com"
  EMAIL_PASS: "dpnznkvpeuytufqe"