apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cake-delight
spec:
  selector:
    app: notification-service
  ports:
    - port: 4004
      targetPort: 4004
  type: ClusterIP