apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  namespace: cake-delight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: subbaiahkv/cakedelight-rating-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4003
          env:
            - name: PORT
              value: "4003"

            - name: MONGO_URI
              value: "mongodb://rating-mongo:27017/rating_db"

            - name: ORDER_SERVICE_URL
              value: "http://order-service:4002"
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 4003
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"