apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mongo
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-mongo
  template:
    metadata:
      labels:
        app: order-mongo
    spec:
      containers:
        - name: order-mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: order-mongo-data
              mountPath: /data/db
      volumes:
        - name: order-mongo-data
          persistentVolumeClaim:
            claimName: order-mongo-pvc